name: Build Markdown
description: Concatenate .md files from a directory into a single document

inputs:
  source-dir:
    description: Path to the directory with .md files
    required: true
  output-file:
    description: Output filename (e.g. DND-SRD-5.2.1-RU.md)
    required: true

runs:
  using: composite
  steps:
    - name: Concatenate markdown files
      shell: bash
      run: |
        find ${{ inputs.source-dir }} -name "*.md" | sort | while read f; do cat "$f"; echo; done > ${{ inputs.output-file }}
